name: Test

on:
  push:
    branches: [ main ]

jobs:
  create-access-token:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Docker Hub access token
        id: create_token
        uses: kantist/docker-hub-create-access-token-action@v1.0.2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          token_label: "temp"
          scopes: "repo:read"
      - name: Echo output of previous step
        run: |
          echo "UUID is: ${{ steps.create_token.outputs.uuid }}"
          echo "Token is: ${{ steps.create_token.outputs.token }}"
      - name: Remove Docker Hub access token created in a previous step
        uses: kantist/docker-hub-remove-access-token-action@v1.0.0
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          uuid: "${{ steps.create_token.outputs.uuid }}"
